// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

/**
 * 
 */
namespace GPS_GameplayTags
{
	// Declare all of the custom native tags we use
	// Ping tags
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ping_Default);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ping_Exclamation);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ping_Question);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ping_Arrow);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ping_Chevron);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ping_X);


	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_Diamond);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_Star);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_Square);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_Exclamation);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_Question);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_Arrow);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_Chevron);
	GENERICPINGSYSTEM_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WorldMarker_X);



}